server:
  port: 9871
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    include: es,redis,quant

logging:
  level:
    org.springframework.web: ERROR
    com.cn.momojie: INFO
  file:
    path: ${APP_LOG_PATH}
    name: app.log
  logback:
    rollingpolicy:
      file-name-pattern: app-%d{yyyy-MM-dd}.%i.log

